version: '2'

services:

    motion:
        image: chalmersfsd/logic-action-motion:pre-release-6432d58
        network_mode: "host"
        command: "motion --cid=${CID} --cidSM=219 --constantSpeed=1 --speedRequest=5.5 --id=1 --verbose=1"

    #proxy-ellipse2n
    #image need to be built locally
    #image imu:latest is using libcluon v0.0.101
    opendlv-proxy-ellipse2n:
        image: proxy-imu:v0.0.101
        network_mode: "host"
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        command: "opendlv-proxy-ellipse2n --cid=${CID} --id=112"

    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=0 --conf$

    odrecorderh264:
       image: ${IMAGE}
       depends_on:
           - odsupercomponent
           - proxy-camera
           - proxy-velodyne16
       volumes:
           - ./recordings:/opt/recordings
       privileged: true
       user: root
       network_mode: host
       ipc: host
       working_dir: "/opt/recordings"
       command: "/opt/od4/bin/odrecorderh264 --cid=${CID}"

