
version: '2'

services:
   odsupercomponent:
       image: ${IMAGE}
       network_mode: host
       volumes:
       - .:/opt/opendlv.data
       command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"
    
   odcockpit:
      image: ${IMAGE}
      network_mode: host
      environment:
      - DISPLAY=$DISPLAY
      volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/opt/opendlv.data
      - ~/recordings:/opt/recordings
      ipc: host
      user: odv
      depends_on:
          - odsupercomponent
      command: "/opt/od4/bin/odcockpit --cid=${CID}"

   cfsd18-sim-visualization:  
      image: chalmersfsd/cfsd18-sim-visualization:pre-release-bd3afa2
      network_mode: "host"
      command: "--cid=${CID}"

